name: mtbek_front
description: MTBEK Frontend
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  # object comparison (all platforms)
  equatable: ^2.0.5
  # dependency injection (all platforms)
  get_it: ^7.6.0
  # code generator for get_it (all platforms)
  injectable: ^2.1.2
  # path provider (all platforms)
  path_provider: ^2.0.15
  #* persistent storage (all platforms)
  shared_preferences: ^2.1.2
  #* state manager (all platforms)
  flutter_bloc: ^8.1.2
  # localization (all platforms)
  easy_localization: ^3.0.2
  #* utils
  # check internet connection
  connectivity_plus: ^4.0.1
  is_first_run: ^1.0.0
  bloc: ^8.1.2
  hive: ^2.2.3
  mask_text_input_formatter: ^2.5.0
  flutter_keyboard_visibility: ^5.4.1
  url_launcher: ^6.2.1
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  skeleton_text: ^3.0.1
  statsfl: ^2.3.0
  custom_date_range_picker: ^1.0.10
  url_strategy: ^0.2.0
  flutter_native_splash: ^2.3.9
  go_router: ^13.0.1
  pretty_dio_logger: ^1.3.1
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # launcher icons
  flutter_launcher_icons: ^0.13.1
  # code generation core (all platforms)
  build_runner: ^2.4.6
  # code generator for injection (all platforms)
  injectable_generator: ^2.1.6
  # for code rules
  flutter_lints: ^2.0.1
  build_web_compilers: ^4.0.6
  another_flushbar: 1.12.31-dev.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/drawer/
    - assets/icons/navigation/
    - assets/images/
    - assets/fonts/
    - assets/translations/

  fonts:
    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf

    - family: OpenSans-Medium
      fonts:
        - asset: assets/fonts/OpenSans-Medium.ttf

    - family: OpenSans-SemiBold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf

    - family: OpenSans-Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
